config/routes.rb
Rails.application.routes.draw do
  root        'static_pages#home'
  get         'signup'    => 'users#new'
  # get 'user/:id' => 'users#show'
  get         'login'     => 'sessions#new'
  post        'login'     => 'sessions#create'
  delete      'logout'    => 'sessions#destroy'
  # get         'settings'  => 'users#edit'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :feedbacks, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to "Home", root_url %>
    <% if logged_in? %>
      <%= link_to "Profile", current_user %>
      <%= link_to "Settings", edit_user_path(current_user) %>
      <%= link_to "Logout", logout_path, method: "delete" %>
    <% elsif request.path != "/login" %>
      <%= render 'sessions/login_form' %>
    <% end %>
  </nav>
</header>

app/views/layouts/_ie.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PUG</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/ie' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>